### ISSUE TITLE
Work in static analysis in a lower level with the machine and the browser

### ISSUE THREAD

**Issue by victor0989** [victor4458776/File-testing#2]
Try to merge and compare files and trace and map the routes of the memory usage and system calls.
See if you can check the browser calls. How we could merge the browser-files logs across linux machines?

Probably, we can use katalon or RPA files and analyze what the browser is doing in a lower level machine to check for memory and speed performance

**Comment by victor4458776** [comment]
I am working hard to fix my tests and work on the RPA functions and hypothesis annotations
@victor4458776
